services:
  trainee-management-api:
    build:
      context: .
      dockerfile: TraineeManagement/Dockerfile
      args:
        DOMAIN_OWNER: ${DOMAIN_OWNER}
        REGION: ${REGION}
        NUGET_REPO_NAME: ${NUGET_REPO_NAME}
        CODEARTIFACT_AUTH_TOKEN: ${CODEARTIFACT_AUTH_TOKEN}
    container_name: traineeManagement
    ports:
      - 5237:8080
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      ConnectionStrings__DefaultConnection: "server=mysql;port=3306;database=trainee_management_db;user=root;password=your_password"
      Redis__ConnectionString: "redis:6379"
      RabbitMQ__HostName: "rabbitmq"
      RabbitMQ__Port: 5672
      RabbitMQ__UserName: "username"
      RabbitMQ__Password: "password"
      RabbitMQ__VirtualHost: "/"
      RabbitMQ__QueueName: "submission-processing"
      RabbitMQ__DeadLetterExchange: "submission-processing-dlx"
      RabbitMQ__DeadLetterQueue: "submission-processing-dlq"
      Storage__RootPath: "../TraineeManagement/Storage"
      TrainingDirectory__BaseUrl: "http://trainingdirectory:8080"
    networks:
    - trainee_management_network
    volumes:
    - storage-data:/TraineeManagement/Storage

  submission-processor:
    build:
      context: .
      dockerfile: SubmissionProcessor/Dockerfile
      args:
        DOMAIN_OWNER: ${DOMAIN_OWNER}
        REGION: ${REGION}
        NUGET_REPO_NAME: ${NUGET_REPO_NAME}
        CODEARTIFACT_AUTH_TOKEN: ${CODEARTIFACT_AUTH_TOKEN}
    container_name: submissionprocessor
    # ports:
    #   - 5238:5237
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      trainee-management-api:
        condition: service_started
    environment:
      ConnectionStrings__DefaultConnection: "server=mysql;port=3306;database=trainee_management_db;user=root;password=your_password"
      Redis__ConnectionString: "redis:6379"
      RabbitMQ__HostName: "rabbitmq"
      RabbitMQ__Port: 5672
      RabbitMQ__UserName: "username"
      RabbitMQ__Password: "password"
      RabbitMQ__VirtualHost: "/"
      RabbitMQ__QueueName: "submission-processing"
      RabbitMQ__DeadLetterExchange: "submission-processing-dlx"
      RabbitMQ__DeadLetterQueue: "submission-processing-dlq"
      Storage__RootPath: "../TraineeManagement/Storage"
      TrainingDirectory__BaseUrl: "http://trainingdirectory:8080"
    networks:
      - trainee_management_network
    volumes:
      - storage-data:/TraineeManagement/Storage
  
  trainingdirectory:
    build:
      context: .
      dockerfile: TrainingDirectory.Api/Dockerfile
      args:
        DOMAIN_OWNER: ${DOMAIN_OWNER}
        REGION: ${REGION}
        NUGET_REPO_NAME: ${NUGET_REPO_NAME}
        CODEARTIFACT_AUTH_TOKEN: ${CODEARTIFACT_AUTH_TOKEN}
    container_name: trainingdirectory
    ports:
      - "5200:8080"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      ConnectionStrings__DefaultConnection: "server=mysql;port=3306;database=trainee_management_db;user=root;password=your_password"
    networks:
      - trainee_management_network
    
  redis:
    image: repository_name/redis:tag
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - trainee_management_network

  mysql:
    image: repository_name/mysql:tag
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-pRoot@123"]
      interval: 10s
      timeout: 5s
      retries: 10
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: Root@123
      MYSQL_DATABASE: trainee_management_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - trainee_management_network

  rabbitmq:
    image: repository_name/rabbitmq:tag
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10
    container_name: rabbitmq
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: default_user
      RABBITMQ_DEFAULT_PASS: default_password
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - trainee_management_network

volumes:
  mysql_data:
  rabbitmq_data:
  storage-data:

networks:
  trainee_management_network: